/**
 * Specs Inc. 2026
 * PremadeQuestions.ts — baked trivia for the premade "cosmos" deck cards.
 *
 * The 37 premade cards in cardDeckData.ts never change, so their battle
 * questions are authored once here instead of being regenerated by an OpenAI
 * call every match. This makes premade questions instant, free, and reliable;
 * only the user-specific CAPTURED-card questions are generated at runtime.
 *
 * Shape matches BattleQuestionGenerator's GeneratedQuestion (minus id, which the
 * MultiplayerTriviaManager assigns at queue-assembly time), so the manager can
 * map these through the same toRecord() path. Correct-answer positions are
 * varied across 1-4 on purpose so players can't pattern-match a single slot.
 *
 * Each question carries BOTH a `roast` (spoken by the host on a wrong answer) and
 * a `praise` (spoken on a correct answer) — short, witty, and specific to the
 * fact, so the host's reaction always fits the question.
 */

export interface BakedQuestion {
  question: string;
  option1: string;
  option2: string;
  option3: string;
  option4: string;
  optionCount: number;
  answer: number; // 1-indexed correct option
  roast: string;  // wrong-answer line
  praise: string; // correct-answer line
}

export const PREMADE_QUESTIONS: BakedQuestion[] = [
  // --- Tokyo --------------------------------------------------------------
  {
    question: "What gives a shrine's copper finials their green coat — the same chemistry that guards the Statue of Liberty?",
    option1: "Rust (iron oxide)", option2: "Algae and moss", option3: "Verdigris, a layer of copper carbonate", option4: "Painted enamel",
    optionCount: 4, answer: 3, roast: "Green with envy at everyone who got that one?", praise: "Correct — you've got a real eye for green.",
  },
  {
    question: "Over the 20th century, Japan's 'kawaii' character design measurably drifted toward what?",
    option1: "Rounder, more infant-like proportions", option2: "Sharper, angular features", option3: "Taller, leaner bodies", option4: "Darker color palettes",
    optionCount: 4, answer: 1, roast: "Too cute to concentrate? That was the easy one.", praise: "Spot on — and adorably so.",
  },
  {
    question: "Why is Kuniyoshi's giant skeleton print so anatomically correct for its era?",
    option1: "He dissected bodies himself", option2: "He copied an older Chinese scroll", option3: "He studied imported Dutch anatomy books", option4: "He simply guessed the bones",
    optionCount: 4, answer: 3, roast: "Bone up before the next round.", praise: "Nailed it, right down to the bones.",
  },
  {
    question: "How does the engawa's raised floor and deep eaves cool a house with no machinery?",
    option1: "Buried blocks of ice", option2: "Reflective gold leaf", option3: "Constant fanning by servants", option4: "Shade plus under-floor airflow (convection)",
    optionCount: 4, answer: 4, roast: "No amount of airflow saves that one.", praise: "Cool, calm, and correct.",
  },
  {
    question: "Japan's 'sabo' engineering became a world model for controlling what?",
    option1: "Earthquakes", option2: "Erosion, floods and debris flows", option3: "Wildfires", option4: "Air pollution",
    optionCount: 4, answer: 2, roast: "That answer washed clean away.", praise: "Correct — that knowledge really holds water.",
  },
  {
    question: "Studying Zen gardens' 'soft fascination' helps design what for astronauts?",
    option1: "Psychologically restorative habitats for long missions", option2: "Faster bullet trains", option3: "Quieter umbrellas", option4: "Brighter streetlights",
    optionCount: 4, answer: 1, roast: "Go find your zen — and a better guess.", praise: "Correct — very zen of you.",
  },
  {
    question: "Why does brush calligraphy change in microgravity?",
    option1: "The brushes simply float away", option2: "Astronauts can't see the paper", option3: "The paper dissolves", option4: "Without gravity pulling ink down the brush, the flow physics change",
    optionCount: 4, answer: 4, roast: "Your answer floated off into orbit.", praise: "Correct — that answer really flows.",
  },
  {
    question: "What mostly melts the thin water film that lets a skate glide?",
    option1: "Pressure-melting alone", option2: "Friction does most of it", option3: "The skater's body heat", option4: "Salt spread on the ice",
    optionCount: 4, answer: 2, roast: "You slipped right off the podium.", praise: "Correct — smooth as fresh ice.",
  },
  {
    question: "Japan's 'gotochi' economy turned local wildlife like the snow-fairy shimaenaga into what?",
    option1: "Protected endangered species", option2: "Zoo-only exhibits", option3: "Branded regional merchandise", option4: "Official postage stamps",
    optionCount: 4, answer: 3, roast: "Even the fluffy bird is side-eyeing you.", praise: "Correct — the fluffy bird approves.",
  },
  {
    question: "Instantly seeing a 'face' in two dots and a line is driven by which brain region?",
    option1: "The fusiform face area", option2: "The cerebellum", option3: "The amygdala", option4: "The hippocampus",
    optionCount: 4, answer: 1, roast: "I can see the face you're making at that score.", praise: "Correct — I can see you smiling.",
  },
  {
    question: "How was 'Space Ram' ramen engineered to fly on the Space Shuttle?",
    option1: "Freeze-dried into hard cubes", option2: "Served completely cold", option3: "Compressed into a paste", option4: "A thickened broth that won't float away",
    optionCount: 4, answer: 4, roast: "That answer? Under-boiled.", praise: "Correct — cooked to perfection.",
  },
  {
    question: "What are Tokyo stations' unique 7-second departure jingles called?",
    option1: "Shinkanson", option2: "Ekimelo", option3: "Bento beats", option4: "Tokyo tones",
    optionCount: 4, answer: 2, roast: "That's your cue to exit — wrong stop.", praise: "Correct — right on cue.",
  },
  {
    question: "The springy rubber that lets you feel tactile paving comes from which tree's latex?",
    option1: "The oak", option2: "Bamboo", option3: "The Hevea rubber tree", option4: "The maple",
    optionCount: 4, answer: 3, roast: "You bounced clean off that one.", praise: "Correct — you bounced right to it.",
  },
  {
    question: "Regional clay figurines sold at train stations are stocked mainly as what?",
    option1: "Omiyage — travel gifts", option2: "Children's playthings", option3: "Religious idols", option4: "Loose-change holders",
    optionCount: 4, answer: 1, roast: "No souvenir for that guess.", praise: "Correct — take a souvenir.",
  },
  {
    question: "What did 2024 genetics finally reveal about orange tabby cats?",
    option1: "They are usually female", option2: "They cannot see orange", option3: "They are all closely related", option4: "Their color comes from a unique X-linked gene",
    optionCount: 4, answer: 4, roast: "That was a cat-astrophe.", praise: "Correct — purr-fectly done.",
  },
  {
    question: "What is 'yarn-bombing,' seen brightening train stations worldwide?",
    option1: "A speed-knitting contest", option2: "Covering public objects in crochet as guerrilla art", option3: "A new kind of commuter train", option4: "An industrial weaving loom",
    optionCount: 4, answer: 2, roast: "You dropped a stitch there.", praise: "Correct — not a stitch out of place.",
  },
  {
    question: "How are some shrines modernizing the omikuji fortune?",
    option1: "Banning it entirely", option2: "Doubling its price", option3: "Dispensing it by app, AR, vending machine or robot", option4: "Only having priests read it aloud",
    optionCount: 4, answer: 3, roast: "Today's omikuji predicted that answer.", praise: "Correct — fortune favors you today.",
  },
  {
    question: "Why are 660cc kei cars so fuel-efficient in city driving?",
    option1: "Low mass and small frontal area beat horsepower", option2: "Oversized turbo engines", option3: "Being fully electric", option4: "Never coming to a stop",
    optionCount: 4, answer: 1, roast: "Running on empty with that one.", praise: "Correct — running on pure efficiency.",
  },
  {
    question: "Why do airlines and canned-coffee makers both over-sweeten their drinks?",
    option1: "It is cheaper to make", option2: "Customers demand it", option3: "Sugar preserves it longer", option4: "Pressure and temperature changes dull taste",
    optionCount: 4, answer: 4, roast: "That guess left a bitter aftertaste.", praise: "Correct — sweet, sweet victory.",
  },
  {
    question: "Airlines re-season their 'sky bento' because cabin pressure does what?",
    option1: "Spoils the rice", option2: "Dulls taste by about 30%", option3: "Freezes the food", option4: "Adds its own salt",
    optionCount: 4, answer: 2, roast: "Even airplane food has more taste than that guess.", praise: "Correct — that one had real flavor.",
  },

  // --- Seattle ------------------------------------------------------------
  {
    question: "Where did Heinz first sell the baked beans now central to a full English breakfast?",
    option1: "A wartime ration depot", option2: "A roadside American diner", option3: "London's upscale Fortnum & Mason (~1901)", option4: "A Boston cannery",
    optionCount: 4, answer: 3, roast: "You don't know beans about this.", praise: "Correct — now you know your beans.",
  },
  {
    question: "The Burke-Gilman Trail past Gas Works Park was paved over what?",
    option1: "An 1880s railroad roadbed", option2: "A filled-in shipping canal", option3: "An old logging highway", option4: "A buried pipeline",
    optionCount: 4, answer: 1, roast: "That answer went right off the rails.", praise: "Correct — right on track.",
  },
  {
    question: "What gives a corgi (and a dachshund) those famously short legs?",
    option1: "A low-protein diet", option2: "Cold Welsh weather", option3: "Centuries of tail-docking", option4: "An extra FGF4 gene copy causing dwarfism",
    optionCount: 4, answer: 4, roast: "Short legs, even shorter on the answer.", praise: "Correct — a big-brain answer on short legs.",
  },
  {
    question: "Why did Dale Chihuly stop blowing glass himself and start directing teams?",
    option1: "He quietly retired young", option2: "A 1976 car crash cost him an eye and his depth perception", option3: "He moved overseas", option4: "He switched to painting",
    optionCount: 4, answer: 2, roast: "Didn't see that one coming either.", praise: "Correct — sharp eye, fittingly.",
  },
  {
    question: "In the wild, the trendy fiddle-leaf fig is really what kind of plant?",
    option1: "A desert succulent", option2: "A floating water plant", option3: "A strangler that envelops and kills its host tree", option4: "A ground-hugging moss",
    optionCount: 4, answer: 3, roast: "Your guess got strangled — very on brand.", praise: "Correct — you didn't get strangled.",
  },
  {
    question: "A fish looking straight up sees the whole world above squeezed into a bright circle called what?",
    option1: "Snell's window (about 97° wide)", option2: "The event horizon", option3: "The vanishing point", option4: "The optical blind spot",
    optionCount: 4, answer: 1, roast: "Your answer's stuck outside Snell's window.", praise: "Correct — clear view through Snell's window.",
  },
  {
    question: "Wild, bitter gourds nearly vanished when which seed-spreaders went extinct?",
    option1: "Dinosaurs", option2: "Giant ground sloths", option3: "Sea turtles", option4: "Ice Age megafauna like mastodons",
    optionCount: 4, answer: 4, roast: "That answer's extinct too.", praise: "Correct — that knowledge isn't extinct.",
  },
  {
    question: "Why is the sunset you watch over Puget Sound basically a mirage?",
    option1: "Pollution tints the sky", option2: "Refraction keeps the disc visible ~2 minutes after it has truly set", option3: "It's only a reflection off the water", option4: "Your eyes simply lag",
    optionCount: 4, answer: 2, roast: "Your answer set two minutes ago.", praise: "Correct — you saw right through it.",
  },
  {
    question: "What did lichens do after ~18 months bolted to the outside of the ISS?",
    option1: "Crumbled to dust", option2: "Mutated into algae", option3: "Resumed living once returned to Earth", option4: "Burned up on re-entry",
    optionCount: 4, answer: 3, roast: "Even space lichen outlasted that guess.", praise: "Correct — out-of-this-world answer.",
  },
  {
    question: "Why do mochi pounders keep a chanted rhythm during 'mochitsuki'?",
    option1: "So the mallet never crushes the hand-flipper", option2: "To attract a crowd", option3: "To time the steaming rice", option4: "Purely for good luck",
    optionCount: 4, answer: 1, roast: "You got pounded on that one.", praise: "Correct — perfect timing.",
  },
  {
    question: "Volunteer Park's 'Black Sun' sculpture supposedly inspired which 1994 hit?",
    option1: "Nirvana's 'Smells Like Teen Spirit'", option2: "Pearl Jam's 'Alive'", option3: "Pearl Jam's 'Jeremy'", option4: "Soundgarden's 'Black Hole Sun'",
    optionCount: 4, answer: 4, roast: "That answer? Black hole. Gone.", praise: "Correct — that one was a hit.",
  },
  {
    question: "The term 'flying saucer' was coined after a 1947 sighting near which peak?",
    option1: "Mount St. Helens", option2: "Mount Rainier", option3: "Mount Hood", option4: "Mount Baker",
    optionCount: 4, answer: 2, roast: "Your answer's the real UFO.", praise: "Correct — no UFO needed.",
  },
  {
    question: "Why can a vintage gas-lantern mantle still trip a Geiger counter?",
    option1: "It's coated in lead paint", option2: "It's filled with leftover propane", option3: "It was soaked in radioactive thorium dioxide", option4: "It's a magnetized steel mesh",
    optionCount: 4, answer: 3, roast: "That answer's radioactive — and wrong.", praise: "Correct — that answer glows.",
  },
  {
    question: "Bending a single wire into a figure, pioneered by Calder, is called what?",
    option1: "'Drawing in space'", option2: "Filigree work", option3: "Cold forging", option4: "Line etching",
    optionCount: 4, answer: 1, roast: "You just drew a blank.", praise: "Correct — you drew that one perfectly.",
  },
  {
    question: "What inspired the very first Little Free Library in 2009?",
    option1: "A city literacy grant", option2: "A neighborhood book-club dare", option3: "A local library closing down", option4: "Todd Bol honoring his late mother, a teacher",
    optionCount: 4, answer: 4, roast: "Return that answer — it's overdue.", praise: "Correct — no late fees for you.",
  },
  {
    question: "Why do a whole city's ornamental cherry trees bloom in near-perfect unison?",
    option1: "They share the same rich soil", option2: "They're a single grafted clone, 'Somei-yoshino'", option3: "Their pruning is synchronized", option4: "A warm spring rain triggers them",
    optionCount: 4, answer: 2, roast: "That answer never blossomed.", praise: "Correct — that answer blossomed.",
  },
  {
    question: "Smart plush toys that come alive in AR via a phone camera create what kind of bridge?",
    option1: "A purely wireless link", option2: "A Bluetooth-only tether", option3: "A 'phygital' bridge — physical doll plus digital world", option4: "A cloud backup of the toy",
    optionCount: 4, answer: 3, roast: "That guess wasn't very 'phygital.'", praise: "Correct — very phygital of you.",
  },
];
